version: '3.3'
services:
  app:
    image: klawx3/ej2
    container_name: 'web-app'
    restart: always
    depends_on:
      - 'db'
    ports: 
      - '3000:3000'
    networks:
      - backend-network
  db:
    image: mariadb
    container_name: 'mariadb-backend'
    restart: always
    environment:
      MYSQL_DATABASE: 'empresa_prueba_tecnica'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    volumes:
      - ./sql_script:/docker-entrypoint-initdb.d
    networks: 
      - backend-network

networks:
  backend-network:
    driver: bridge